BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://jling.tk/link/
  theme: butterfly
- link: https://nie.su/links.html/
  theme: butterfly
MAX_POSTS_NUM: 10
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u6728\u6728\u6728\u6728\u6728"
    - https://immmmm.com/
    - https://cravatar.cn/avatar/ba83fa02fc4b2ba621514941307e21be
  - - "\u9ED1\u77F3\u535A\u5BA2"
    - https://www.heson10.com/
    - https://akilar.top/images/headimage.png
  - - "\u6D85\u69C3\u535A\u5BA2"
    - https://nie.su/
    - https://cravatar.cn/avatar/2bb6abe8f8067dcc29839dc67e98cf84
  - - "\u7CBE\u7075\u5BA2\u6808"
    - https://jling.tk/
    - https://cravatar.cn/avatar/c4vqso4m1ualpgq8185h9g9d3d
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - "\u6D6E\u4E91\u7FE9\u8FC1\u4E4B\u95F4"
    - https://blognas.hwb0307.com/
    - https://blognas.hwb0307.com/logo.jpg
  - - "\u4E66\u82D1\u7F51\u6587\u7CBE\u6392\u793E"
    - https://nicepub.top/
    - https://gcore.jsdelivr.net/gh/love2wind/cloudimg/img/e281e8b803d9efc9baf360f90de0c942.webp
  - - "\u79E6\u67AB\u9E22\u68A6"
    - https://blog.zwying.com/
    - https://blog.zwying.com/avatar.jpg
  - - "\u56CD\u697D\u4E91\u535A\u5BA2"
    - https://boke.2lc.top/
    - https://thirdqq.qlogo.cn/g?b=qq&nk=3038733136&s=100
  - - "\u98CE\u547C\u547C"
    - http://whooc.com/
    - http://whooc.com/logo
